class Dynometry < ApplicationRecord
    validates :peak_extension_right, presence: true
    validates :peak_extension_left, presence: true
    validates :peak_extension_deficit, presence: true
    validates :peak_flexion_right, presence: true
    validates :peak_flexion_left, presence: true
    validates :peak_flexion_deficit, presence: true
    validates :power_extension_right_180, presence: true
    validates :power_extension_left_180, presence: true
    validates :power_extension_deficit_180, presence: true
    validates :power_flexion_right_180, presence: true
    validates :power_flexion_left_180, presence: true
    validates :power_flexion_deficit_180, presence: true
    validates :power_extension_right_300, presence: true
    validates :power_extension_left_300, presence: true
    validates :power_extesion_deficit_300, presence: true
    validates :power_flexion_right_300, presence: true
    validates :power_flexion_left_300, presence: true
    validates :power_flexion_deficit_300, presence: true
    validates :job_extension_right_180, presence: true
    validates :job_extension_left_180, presence: true
    validates :job_extesion_deficit_180, presence: true
    validates :job_flexion_right_180, presence: true
    validates :job_flexion_left_180, presence: true
    validates :job_flexion_deficit_180, presence: true
    validates :job_extension_right_300, presence: true
    validates :job_extension_left_300, presence: true
    validates :job_extesion_deficit_300, presence: true
    validates :job_flexion_right_300, presence: true
    validates :job_flexion_left_300, presence: true
    validates :job_flexion_deficit_300, presence: true
    validates :fatigue_extension_right_300, presence: true
    validates :fatigue_extension_left_300, presence: true
    validates :fatigue_extesion_deficit_300, presence: true
    validates :fatigue_flexion_right_300, presence: true
    validates :fatigue_flexion_left_300, presence: true
    validates :fatigue_flexion_deficit_300, presence: true
    validates :IDM_extension, presence: true
    validates :IDM_flexion, presence: true
    validates :relation_extension_right, presence: true
    validates :relation_extension_left, presence: true
end
